import '@/app/globals.css'; 
import { MinutesProvider } from "@/contexts/MinutesContext";
import { HistoryProvider } from "@/contexts/HistoryContext";

export const metadata = {
  title: 'Video Insights',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <HistoryProvider>
        <MinutesProvider>
          {children}
        </MinutesProvider>
      </HistoryProvider>
      </body>
    </html>
  )
}
