import '@/app/globals.css'; 
import { MinutesProvider } from "@/contexts/MinutesContext";

export const metadata = {
  title: 'Video Insights',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <MinutesProvider>
        {children}
      </MinutesProvider>
      </body>
    </html>
  )
}
