import '@/app/globals.css'; 

export const metadata = {
  title: 'Video Insights',
  description: 'Generated by Next.js',
}

export default function UploadLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <>{children}</>;
}
